[package]
name = "taskmaster"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
rustyline = "10.0"
signal-hook = "0.3"
libc = "0.2"
