programs:
  test:
    cmd: "tail -f /dev/null"
    numprocs: 1
    umask: 022
    workingdir: /tmp
    autostart: true
    autorestart: unexpected
    exitcodes:
      - 0
      - 2
    startretries: 3
    starttime: 5
    stopsignal: TERM
    stoptime: 10
    stdout: /tmp/taskmaster1.stdout
    stderr: /tmp/taskmaster1.stderr
    env:
      STARTED_BY: taskmaster
      ANSWER: 42
  while:
    cmd: "while true; do echo 'Running...'; sleep 5; done"
    numprocs: 8
    umask: 077
    workingdir: /tmp
    autostart: true
    autorestart: unexpected
    exitcodes:
      - 0
    startretries: 3
    starttime: 5
    stopsignal: USR1
    stoptime: 10
    stdout: /tmp/taskmaster2.stdout
    stderr: /tmp/taskmaster2.stderr
